### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by jatpat** [srigaurav1986/KurentoExample#1]
Hi,

I visited issue at [https://github.com/miroof/kurento-composite-node-example/issues/2](https://github.com/miroof/kurento-composite-node-example/issues/2)

And as per your comment I run your code, but facing one issue when I click on start button for recording it is giving me error.

I have attached screenshot.  Can you help me to solve issue?

![kurento error](https://cloud.githubusercontent.com/assets/6779382/13463681/74cf1486-e0b3-11e5-95e7-6aa047f093d0.png)

**Comment by srigaurav1986** [comment]
Hi Jatpat
In this example we have one client and app server(server.js), as obvious u r getting crash in app server code.
This crash happens when client sends the media sdp to application server  which it accepts and forward to Kurento media server(KMS). KMS does some processing,creates one resource for the client and returns this resource details to application server. After receiving the response from KMS, app server use those credentials to address further requests coming from client, but  if app server replies to client's request before getting response from KMS, due to unavailability of resource's details it crashes.This is occurring in your scenario. 

I wanted to write very simple server application hence avoided synchronization complexity. If you want to avoid this crash use can integrate Promise library in app server code and before receiving ICE candidates req from client ensure that app server has received response from KMS about the resource details.

May be u can setup this example on the m/c where KMS is installed. In that case KMS resp would reach to app server before client's further requests and ur issue won't occur.

Thanks and Regards,
srigaurav1986

**Comment by jatpat** [comment]
Hi srigaurav1986,

Error is resolved there was dependency version issue and hence ICE was not synchronised.

I have one query, I modified code to record composite stream but the file is blank, media server is not recording at all.  I have attached screenshot.  can you help me, what is wrong?

![kurento recording doubt](https://cloud.githubusercontent.com/assets/6779382/13547414/b3a9ac66-e2f7-11e5-8722-9b1836c50725.png)

Thanks for your help.

**Comment by srigaurav1986** [comment]
Jatpat,

I am glad your issue is resolved now, would request to share the exact solution so that I can close this thread.

Regarding recording please initiate a separate bug , so that tracking would be easier for everyone , after all its a open source :).

Thanks,srigaurav1986

**Comment by jatpat** [comment]
Hi srigaurav1986,

Actually, Due to some error npm was not able to import and build dependency modules.   There was no single error in your code, but dependency nodejs modules from where I copied had different version of what it was needed for this project.

As I copied specific version modules from another project it started working.

Thank.
